version: '3.7'
services:
  url-shortener-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: url-shortener-api
    container_name: url-shortener-api
    ports:
      - "3333:3333"
      - "7778:7777"
    env_file:
     - ./dev.env
    volumes:
      - .:/app
      - node_modules
    links:
      - url-shortener-db
      - url-shortener-redis
  url-shortener-client:
    build:
      context: .
      dockerfile: client.Dockerfile
    image: url-shortener-client
    container_name: url-shortener-client
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules
    links:
      - url-shortener-api
  url-shortener-db:
    container_name: url-shortener-db
    image: postgres:9.6.16
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
  url-shortener-redis:
    container_name: url-shortener-redis
    image: redis:6.2.5
    ports:
     - "6379:6379"
