version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-browsers

npm_install: &npm_install
  name: Install Dependencies
  command: npm install

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *npm_install
  check-formatting:
    <<: *defaults
    steps:
      - checkout
      - run: npm run format:check
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  pipeline:
    jobs:
      - install
      - check-formatting:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
